### PR TITLE
Upgrade to v0.5.1 and convert to NoArch Build

### PR DESCRIPTION
**Pull request by rxm7706**
1. fixed orjson deps to match source.
2. make the package no arch - by managing the single windows only dependency win-precise-time

closes https://github.com/conda-forge/dlt-feedstock/pull/9

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

see sample - that avoids building arch specific builds - by specifying arch selectors
  - https://github.com/conda-forge/pypac-feedstock/blob/main/recipe/meta.yaml 
  - the default linter error is managed by adding the selectors to conda-forge.yml

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @rudolfix @sultaniman - can you please review and merge. Description of the PR includes changes, and comments. 
Thank you and regards.

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @rudolfix @sultaniman - can you please review and merge. Description of the PR includes changes, and comments.
I have added myself as a co-maintainer, if you need assistance, please feel free to remove me - if you do not need help.
Thank you and regards.

**Comment by sultaniman** [comment]
@rxm7706 please update to the latest version

**Comment by rxm7706** [comment]
> @rxm7706 please update to the latest version
Sure @sultaniman , thank you. 
Testing locally - will raise another PR for the latest version.

**Pull request closed without merging**
